# Generated by Django 5.2.7 on 2025-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_date_of_birth_user_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
