# Generated by Django 5.2.8 on 2025-11-26 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
