# Generated by Django 5.2.8 on 2025-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courseevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
