# Generated by Django 5.2.8 on 2025-11-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_questionreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturequestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionreply',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
