# Generated by Django 5.2.8 on 2025-11-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_liveclassattendance_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseevent',
            name='date',
        ),
    ]
