# Generated by Django 5.2.8 on 2025-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_courseevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevent',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
