# Generated by Django 5.2.9 on 2025-12-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseevent_reminder_sent_liveclass_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
    ]
