# Generated by Django 5.2.9 on 2025-12-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_rename_feedback_text_feedback_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
