# Generated by Django 5.2.8 on 2025-12-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_lecture_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='order',
            new_name='assignment_order',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='order',
            new_name='lecture_order',
        ),
        migrations.RenameField(
            model_name='liveclass',
            old_name='order',
            new_name='live_order',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='module_order',
        ),
        migrations.RemoveField(
            model_name='courseblock',
            name='order',
        ),
        migrations.AddField(
            model_name='courseblock',
            name='block_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
